version: "3.1"
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
services:
      app-cole-test:
            build: .
            container_name : app-cole-test
            restart: always
            ports: 
                  - "8080:80"
            volumes:
                  - ./html:/var/www/html
            networks:
                  custom_net:
                        ipv4_address: 10.5.0.2
      db-cole-test:
            container_name : db-cole-test
            image: mysql:8.0
            restart: always
            ports: 
                  - "3306:3306"     
            environment:
                  MYSQL_DATABASE: cole
                  MYSQL_USER: cole
                  MYSQL_PASSWORD: cole.002
                  MYSQL_ROOT_PASSWORD: cole.001
            volumes:               
                  - "./html/mysql:/var/lib/mysql"      
            networks:
                  custom_net:
                        ipv4_address: 10.5.0.3
      phpmyadmin-test:
            depends_on:
                  - db-cole-test
            image: phpmyadmin
            restart: always
            ports:
                  - "8090:80"
            environment:
                  PMA_HOST: db-cole
                  MYSQL_ROOT_PASSWORD: cole.001
            networks:
                  custom_net:
                        ipv4_address: 10.5.0.4
    

