version: "3.1"
services:
      app-cole:
            build: .
            container_name : app-cole
            restart: always
            ports: 
                  - "8080:80"
            volumes:
                  - ./html/app:/var/www/html
            networks:
                  - default 
      
      db-cole:
            container_name : db-cole
            command: mysqld --default-authentication-plugin=mysql_native_password
            image: mysql:8.0
            restart: always
            ports: 
                  - "3307:3306"     
            environment:
                  MYSQL_DATABASE: cole
                  MYSQL_USER: cole
                  MYSQL_PASSWORD: cole.001
                  MYSQL_ROOT_PASSWORD: cole.001 
            volumes:               
                  - "./html/sql/var:/var/lib/mysql"      
            networks:
                  - default
    

