version: "3.1"
services:
      app-cole:
            build: .
            container_name : app-cole
            restart: always
            ports: 
                  - "8080:80"
            volumes:
                  - ./html/app:/var/www/html
            networks:
                  - default 
      
      db-cole:
            container_name : db-cole
            image: mysql:8.0
            restart: always
            ports: 
                  - "3306:3306"     
            environment:
                  MYSQL_DATABASE: cole
                  MYSQL_USER: cole
                  MYSQL_PASSWORD: cole.002
                  MYSQL_ROOT_PASSWORD: cole.001
            volumes:               
                  - "./html/sql/var:/var/lib/mysql"      
            networks:
                  - default
      phpmyadmin:
            depends_on:
                  - db-cole
            image: phpmyadmin
            restart: always
            ports:
                  - "8090:80"
            environment:
                  PMA_HOST: db-cole
                  MYSQL_ROOT_PASSWORD: cole.001
            networks:
                  - default
    

